### ISSUE TITLE
Test that skip-limit / retry-limit of 0 mean don't skip/retry at all.

### ISSUE THREAD

**Issue by scottkurz** [WASdev/standards.jsr352.tck#19]
Esp. since start-limit=0 means no-limit...worth clarifying.

**Comment by jvfullam** [comment]
Test added for skip-limit=0 in c3ddc31

I will add a similar test for retry-limit=0 soon

**Comment by jvfullam** [comment]
I think it would also be good to add a test that causes the skip-limit to be reached by throwing exceptions from a combination of the reader/ processor/ writer. For example: skip-limit=2, reader throws 1 skippable exception, processor throws 1 skippable exception, and writer throws 1 skippable exception --> skip-limit is exceeded by the writer's exception, verify that the job fails.

**Comment by scottkurz** [comment]
Good idea (to test against the aggregate count).  Thanks for the contribution.
