### ISSUE TITLE
Download and Documentation links are stale

### ISSUE THREAD

**Issue by edbratt** [WASdev/standards.jsr352.tck#68]
The Documentation and Download links point to java.net which has been shut-down for awhile now. Please refresh these URLs with the current locations.

**Comment by scottkurz** [comment]
@edbratt -Thanks for noting this.

 I updated [this](https://github.com/WASdev/standards.jsr352.tck/wiki/1.0_SE_TCK_Official) and [this](https://github.com/WASdev/standards.jsr352.tck/wiki/1.0_SE_TCK_ChangeHistory) link on the Wiki to at least have some reference to the latest download [SE TCK zip](https://github.com/WASdev/standards.jsr352.tck/blob/1.0.x/releases/jsr352-tck-1.0.zip?raw=true) and the original [Reference Guide](https://github.com/WASdev/standards.jsr352.tck/blob/1.0.x/docs/jsr352-tck-reference-guide.pdf).  

I think this maybe provides a bare minimum access to this.   

Obviously there's a lot that could be improved, but in the meantime if there's something else specific you were looking for, please add a comment.

**Comment by edbratt** [comment]
That's much better and good enough for now. Thanks!
